export const GET_GAMES_BEGIN = "GET_GAMES_BEGIN";
export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS";
export const GET_GAMES_FAIL = "GET_GAMES_FAIL";

export const GET_GAMES_DETAIL_BEGIN = "GET_GAMES_DETAIL_BEGIN";
export const GET_GAMES_DETAIL_SUCCESS = "GET_GAMES_DETAIL_SUCCESS";
export const GET_GAMES_DETAIL_FAIL = "GET_GAMES_DETAIL_FAIL";

export const GET_GENRES_BEGIN = "GET_GENRES_BEGIN";
export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";
export const GET_GENRES_FAIL = "GET_GENRES_FAIL";

export const GET_GAMES_BY_GENRE_BEGIN = "GET_GAMES_BY_GENRE_BEGIN";
export const GET_GAMES_BY_GENRE_SUCCESS = "GET_GAMES_BY_GENRE_SUCCESS";
export const GET_GAMES_BY_GENRE_FAIL = "GET_GAMES_BY_GENRE_FAIL";

export const SEARCH_GAMES_BEGIN = "SEARCH_GAMES_BEGIN";
export const SEARCH_GAMES_SUCCESS = "SEARCH_GAMES_SUCCESS";
export const SEARCH_GAMES_FAIL = "SEARCH_GAMES_FAIL";

export const CLEAR = "CLEAR";
