export const GET_GAMES_BEGIN = "GET_GAMES_BEGIN";
export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS";
export const GET_GAMES_FAIL = "GET_GAMES_FAIL";

export const GET_GAMES_DETAIL_BEGIN = "GET_GAMES_DETAIL_BEGIN";
export const GET_GAMES_DETAIL_SUCCESS = "GET_GAMES_DETAIL_SUCCESS";
export const GET_GAMES_DETAIL_FAIL = "GET_GAMES_DETAIL_FAIL";

export const GET_GENRES_BEGIN = "GET_GENRES_BEGIN";
export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";
export const GET_GENRES_FAIL = "GET_GENRES_FAIL";
